// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankId} from "./BankId";

/**
 * Create a new bank account for user.
 */
export type BankAccountForm = { bankId: BankId, accountNumber: string, accountName: string, isDefault?: boolean, countryId: string, verificationImage?: string, };
