// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankAccountView} from "./BankAccountView";

/**
 * Bank account operation response.
 */
export type BankAccountOperationResponse = { bankAccount: BankAccountView, success: boolean, };
