// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {WorkflowId} from "./WorkflowId";
import type {WorkflowStatus} from "./WorkflowStatus";

/**
 * Cancel a workflow job
 */
export type CancelJobForm = { seqNumber: number, workflowId: WorkflowId, reason?: string, currentStatus: WorkflowStatus, };
