// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {PersonBan} from "./PersonBan";
import type {TagsView} from "./TagsView";

/**
 * A category view.
 */
export type CategoryView = { category: Category, 
/**
 * Renamed from the old per-instance actions embed (your own block/ban state);
 * `#[serde(rename)]` keeps the wire shape unchanged now that the Rust-side type/field is
 * `person_ban`/`PersonBan` (only the ban half of the old embed survives -- blocking was
 * dead).
 */
instanceActions?: PersonBan, canMod: boolean, postTags: TagsView, };
