// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The category sort types.
 */
export type CategorySortType =
  | "ActiveSixMonths"
  | "ActiveMonthly"
  | "ActiveWeekly"
  | "ActiveDaily"
  | "Hot"
  | "New"
  | "Old"
  | "NameAsc"
  | "NameDesc"
  | "Proposals"
  | "Posts"
  | "Subscribers"
  | "SubscribersLocal";
