// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Parameter for setting category icon or banner. `Query<CategoryIdQuery>` is used on the link
 * (POST) side to keep the category id separate from the JSON `{assetId}` body; delete uses
 * `Json<CategoryIdQuery>` with the id in the body instead.
 */
export type CategoryIdQuery = { id: CategoryId, };
