// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Proposal} from "./Proposal";
import type {ProposalActions} from "./ProposalActions";
import type {Category} from "./Category";
import type {CategoryActions} from "./CategoryActions";
import type {InstanceActions} from "./InstanceActions";
import type {Person} from "./Person";
import type {PersonActions} from "./PersonActions";
import type {Post} from "./Post";
import type {TagsView} from "./TagsView";

/**
 * A proposal view (formerly CommentView — backend calls this ProposalView).
 */
export type CommentView = {
    proposal: Proposal;
    creator: Person;
    post: Post;
    category: Category;
    categoryActions?: CategoryActions;
    proposalActions?: ProposalActions;
    personActions?: PersonActions;
    instanceActions?: InstanceActions;
    creatorIsAdmin: boolean;
    postTags: TagsView;
    canMod: boolean;
    creatorBanned: boolean;
    creatorIsModerator: boolean;
    creatorBannedFromCategory: boolean;
};
