// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {CategoryVisibility} from "./CategoryVisibility";

/**
 * Create a category.
 */
export type CreateCategory = {
    /**
     * The unique name.
     */
    name: string;
    /**
     * A longer title.
     */
    title: string;
    /**
     * The parent to nest this category under. Omit to create a root category.
     */
    parentId?: CategoryId;
    /**
     * A sidebar for the category in markdown.
     */
    sidebar?: string;
    /**
     * A shorter, one line description of your category.
     */
    description?: string;
    /**
     * An icon URL.
     */
    icon?: string;
    /**
     * A banner URL.
     */
    banner?: string;
    /**
     * Whether its a self-promotion category.
     */
    selfPromotion?: boolean;
    /**
     * Whether to restrict posting only to moderators.
     */
    postingRestrictedToMods?: boolean;
    visibility?: CategoryVisibility;
};
