// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {VehicleType} from "./VehicleType";

/**
 * Payload for updating delivery details via API.
 * This is a flattened version without nested Option<> for easier API usage.
 * Only fields that should be updatable after post creation are included.
 */
export type DeliveryDetailsPayload = { pickupAddress?: string, pickupLat?: number, pickupLng?: number, dropoffAddress?: string, dropoffLat?: number, dropoffLng?: number, packageDescription?: string, packageWeightKg?: number, packageSize?: string, fragile?: boolean, requiresSignature?: boolean, vehicleRequired?: VehicleType, latestPickupAt?: string, latestDropoffAt?: string, senderName?: string, senderPhone?: string, receiverName?: string, receiverPhone?: string, cashOnDelivery?: boolean, codAmount?: number, };
