// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Coin} from "./Coin";
import type {DeliveryDetailsId} from "./DeliveryDetailsId";
import type {PostId} from "./PostId";
import type {RiderId} from "./RiderId";
import type {TripStatus} from "./TripStatus";

/**
 * Public version of delivery details - excludes sensitive contact information.
 * This is what general users see when viewing a delivery post.
 */
export type DeliveryDetailsPublic = { id: DeliveryDetailsId, postId: PostId, pickupAddress: string, pickupLat?: number, pickupLng?: number, dropoffAddress: string, dropoffLat?: number, dropoffLng?: number, packageDescription?: string, packageWeightKg?: number, packageSize?: string, fragile: boolean, requiresSignature: boolean, vehicleRequired: string, latestPickupAt?: string, latestDropoffAt?: string, cashOnDelivery: boolean, deliveryFee: Coin, employerConfirmedAt?: string, status: TripStatus, assignedRiderId?: RiderId, assignedAt?: string, createdAt: string, updatedAt: string, };
