// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ProposalId} from "./ProposalId";
import type {ProposalSortType} from "./ProposalSortType";
import type {CategoryId} from "./CategoryId";
import type {ListingType} from "./ListingType";
import type {PaginationCursor} from "./PaginationCursor";
import type {PostId} from "./PostId";

/**
 * Get a list of comments.
 */
export type GetComments = {
  type_?: ListingType;
  sort?: ProposalSortType;
  /**
   * Filter to within a given time range, in seconds.
   * IE 60 would give results for the past minute.
   */
  timeRangeSeconds?: number;
  maxDepth?: number;
  pageCursor?: PaginationCursor;
  pageBack?: boolean;
  limit?: number;
  categoryId?: CategoryId;
  categoryName?: string;
  postId?: PostId;
  parentId?: ProposalId;
};
