// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryView} from "./CategoryView";
import type {PostLogisticsView} from "./PostLogisticsView";
import type {PostView} from "./PostView";

/**
 * The post response.
 */
export type GetPostResponse = { postView: PostView, categoryView?: CategoryView, 
/**
 * A list of cross-posts, or other times / communities this link has been posted to.
 */
crossPosts: Array<PostView>, 
/**
 * Unified logistics view for Delivery or Ride posts (None for Normal)
 */
logistics?: PostLogisticsView, };
