// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryView} from "./CategoryView";
import type {PostView} from "./PostView";

/**
 * The post response.
 */
export type GetPostResponse = {
  postView: PostView;
  /**
   * Optional for delivery posts (which rely on post_kind for distinction).
   * Matches `pub category_view: Option<CategoryView>` in api-108jobs
   * crates/db/src/source/post_view/api.rs.
   */
  categoryView?: CategoryView;
  /**
   * A list of cross-posts, or other times / categories this link has been posted to.
   */
  crossPosts: Array<PostView>;
};
