// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ProposalId} from "./ProposalId";
import type {PostId} from "./PostId";

/**
 * Get a post. Needs either the post id, or comment_id.
 */
export type GetPost = {
  id?: PostId;
  proposalId?: ProposalId;
};
