// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ListingType} from "./ListingType";
import type {LocalUserId} from "./LocalUserId";
import type {PersonId} from "./PersonId";
import type {PostListingMode} from "./PostListingMode";
import type {PostSortType} from "./PostSortType";
import type {ProposalSortType} from "./ProposalSortType";
import type {SensitiveString} from "./SensitiveString";
import type {VoteShow} from "./VoteShow";

/**
 * A local profile.
 */
export type LocalUser = {
  id: LocalUserId;
  /**
   * The person_id for the local profile.
   */
  personId: PersonId;
  email?: SensitiveString;
  /**
   * Whether to show NSFW content.
   */
  showNsfw: boolean;
  theme: string;
  defaultPostSortType: PostSortType;
  defaultListingType: ListingType;
  interfaceLanguage: string;
  /**
   * Whether to show avatars.
   */
  showAvatars: boolean;
  sendNotificationsToEmail: boolean;
  /**
   * Whether to show bot accounts.
   */
  showBotAccounts: boolean;
  /**
   * Whether to show read posts.
   */
  showReadPosts: boolean;
  /**
   * Whether their email has been verified.
   */
  emailVerified: boolean;
  /**
   * Whether their registration application has been accepted.
   */
  acceptedTerms: boolean;
  /**
   * Open links in a new tab.
   */
  openLinksInNewTab: boolean;
  blurNsfw: boolean;
  /**
   * Whether infinite scroll is enabled.
   */
  infiniteScrollEnabled: boolean;
  /**
   * Whether the person is an admin.
   */
  admin: boolean;
  /**
   * A post-view mode that changes how multiple post listings look.
   */
  postListingMode: PostListingMode;
  totp2faEnabled: boolean;
  /**
   * Whether to allow keyboard navigation (for browsing and interacting with posts and proposals).
   */
  enableKeyboardNavigation: boolean;
  /**
   * Whether profile avatars and inline images in the UI that are gifs should be allowed to play or
   * should be paused
   */
  enableAnimatedImages: boolean;
  /**
   * Whether a profile can send / receive private messages
   */
  enablePrivateMessages: boolean;
  /**
   * Whether to auto-collapse bot proposals.
   */
  collapseBotProposals: boolean;
  defaultProposalSortType: ProposalSortType;
  /**
   * Whether to automatically mark fetched posts as read.
   */
  autoMarkFetchedPostsAsRead: boolean;
  /**
   * The last time a donation request was shown to this profile. If this is more than a year ago,
   * a new notification request should be shown.
   */
  lastDonationNotificationAt: string;
  /**
   * Whether to hide posts containing images/videos
   */
  hideMedia: boolean;
  /**
   * A default time range limit to apply to post sorts, in seconds.
   */
  defaultPostTimeRangeSeconds?: number;
  showScore: boolean;
  showUpvotes: boolean;
  showDownvotes: VoteShow;
  showUpvotePercentage: boolean;
  showPersonVotes: boolean;
  /**
   * Whether this account's chat messages are encrypted in transit.
   *
   * Not end-to-end: 108jobs holds the key so it can relay and moderate.
   */
  secureChatEnabled: boolean;
};
