// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire response for the two badge-count endpoints: `GET
 * /api/v4/notifications/unread-count` and `GET
 * /api/v4/admin/notifications/unresolved-count`.
 */
export type NotificationCountResponse = { count: bigint, };
