// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A role a notification can be addressed to, instead of one person.
 */
export type NotificationRole = "Admin";
