// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserId } from "./LocalUserId";
import type { NotificationId } from "./NotificationId";
import type { NotificationKind } from "./NotificationKind";
import type { NotificationRole } from "./NotificationRole";
import type { RiderDecisionId } from "./RiderDecisionId";
import type { RiderId } from "./RiderId";

/**
 * One notification, either personal or addressed to a role.
 *
 * A personal row is READ by its owner; a role row is RESOLVED by whoever acts
 * on it. Neither borrows the other's lifecycle, and the
 * `notification_recipient_lifecycle` CHECK refuses the mixture.
 */
export type Notification = { id: NotificationId, sourceEventId: string, kind: NotificationKind, recipientLocalUserId: LocalUserId | null, recipientRole: NotificationRole | null, riderId: RiderId | null, riderDecisionId: RiderDecisionId | null, createdAt: string, readAt: string | null, resolvedAt: string | null, resolvedByLocalUserId: LocalUserId | null, };
