// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiderVerificationStatus } from "./RiderVerificationStatus";

/**
 * The `rider_decision` a notification points at, as it read the moment
 * THAT decision was made -- never the live `rider_rejection_issue` rows,
 * which a later decision may since have overwritten.
 */
export type NotificationDecisionSnapshot = { outcome: RiderVerificationStatus, 
/**
 * `[{document, reason, ordinal}]` as it read at decision time. Displayed,
 * never queried -- see `RiderDecision::issues`.
 */
issues: unknown, };
