// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationWithDecision } from "./NotificationWithDecision";

/**
 * Wire response for `GET /api/v4/notifications` and
 * `GET /api/v4/admin/notifications`.
 */
export type NotificationListResponse = { notifications: Array<NotificationWithDecision>, };
