// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserId } from "./LocalUserId";
import type { NotificationDecisionSnapshot } from "./NotificationDecisionSnapshot";
import type { NotificationId } from "./NotificationId";
import type { NotificationKind } from "./NotificationKind";
import type { NotificationRole } from "./NotificationRole";
import type { RiderDecisionId } from "./RiderDecisionId";
import type { RiderId } from "./RiderId";

/**
 * One notification, its decision snapshot inlined when it has one.
 *
 * Additive over `Notification`: `#[serde(flatten)]` keeps every existing
 * field at the same JSON level a client already reads, and `decision` is
 * the only new key. Present only for the two kinds
 * `notification_decision_pairing` allows to carry a `rider_decision_id` at
 * all (`RiderApplicationApproved`/`RiderApplicationRejected`); absent for
 * every other kind. Without this, a client rendering a rejection
 * notification had no way to reach its own decision and had to fall back to
 * the rider's LIVE status -- which a later decision may since have
 * overwritten (see `Notification::attach_decisions`).
 */
export type NotificationWithDecision = { decision?: NotificationDecisionSnapshot, id: NotificationId, sourceEventId: string, kind: NotificationKind, recipientLocalUserId: LocalUserId | null, recipientRole: NotificationRole | null, riderId: RiderId | null, riderDecisionId: RiderDecisionId | null, createdAt: string, readAt: string | null, resolvedAt: string | null, resolvedByLocalUserId: LocalUserId | null, };
