// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {DbUrl} from "./DbUrl";
import type {InstanceId} from "./InstanceId";
import type {PersonId} from "./PersonId";
import {WorkSample} from "./WorkSample";
import {PortfolioPic} from "./PortfolioPic";

/**
 * A person.
 */
export type Person = {
    id: PersonId;
    name: string;
    /**
     * A shorter display name.
     */
    displayName?: string;
    /**
     * A URL for an avatar.
     */
    avatar?: DbUrl;
    publishedAt: string;
    updatedAt?: string;
    /**
     * An optional bio, in markdown.
     */
    bio?: string;
    /**
     * A URL for a banner.
     */
    banner?: DbUrl;
    /**
     * A URL for the person's uploaded resume/CV file.
     */
    resumeUrl?: DbUrl;
    /**
     * The original filename of the uploaded resume, shown next to the download link.
     */
    resumeFileName?: string;
    /**
     * Whether the person is deleted.
     */
    deleted: boolean;
    /**
     * A matrix id, usually given an @person:matrix.org
     */
    matrixUserId?: string;
    /**
     * Whether the person is a bot account.
     */
    botAccount: boolean;
    instanceId: InstanceId;
    postCount: number;
    commentCount: number;

    /** === Extra business fields === */
    averageResponseTime: string | null;
    membershipLevelId: string;
    isVerified: string;
    ratings?: number;
    walletId: string;
    contacts?: string;
    skills?: string;
    portfolioPics?: Array<PortfolioPic>;
    workSamples?: Array<WorkSample>
    /**
     * Whether you are currently available for new jobs
     */
    available: boolean;
};
