// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a person is currently banned from the (single) site. A row exists iff the person is
 * banned -- this is the single-instance replacement for the old per-instance actions table's ban
 * half (the old per-instance dimension is gone, since with one instance it was always the same
 * value).
 */
export type PersonBan = { 
/**
 * When the person was banned.
 */
receivedBanAt: string, 
/**
 * When their ban expires.
 */
banExpiresAt: string | null, };
