// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CoinId} from "./CoinId";
import type {DbUrl} from "./DbUrl";
import type {ListingType} from "./ListingType";
import type {LocalSiteId} from "./LocalSiteId";
import type {PostListingMode} from "./PostListingMode";
import type {PostSortType} from "./PostSortType";
import type {ProposalSortType} from "./ProposalSortType";
import type {RegistrationMode} from "./RegistrationMode";

/**
 * The platform-wide configuration. Single-tenant: there is exactly one row.
 */
export type PlatformConfig = {
  id: LocalSiteId;
  /**
   * True if the site is set up.
   */
  siteSetup: boolean;
  /**
   * Whether only admins can create communities.
   */
  categoryCreationAdminOnly: boolean;
  /**
   * Whether emails are required.
   */
  requireEmailVerification: boolean;
  /**
   * An optional registration application questionnaire in markdown.
   */
  applicationQuestion?: string;
  /**
   * The default front-end theme.
   */
  defaultTheme: string;
  defaultPostListingType: ListingType;
  /**
   * An optional legal disclaimer page.
   */
  legalInformation?: string;
  /**
   * Whether new applications multilang admins.
   */
  applicationEmailAdmins: boolean;
  /**
   * An optional regex to filter words.
   */
  slurFilterRegex?: string;
  /**
   * The max actor name length.
   */
  actorNameMaxLength: number;
  publishedAt: string;
  updatedAt?: string;
  registrationMode: RegistrationMode;
  /**
   * Whether to multilang admins on new reports.
   */
  reportsEmailAdmins: boolean;
  /**
   * Default value for [PlatformConfig.post_listing_mode]
   */
  defaultPostListingMode: PostListingMode;
  /**
   * Default value for [LocalUser.post_sort_type]
   */
  defaultPostSortType: PostSortType;
  /**
   * Default value for [LocalUser.proposal_sort_type]
   */
  defaultProposalSortType: ProposalSortType;
  /**
   * Whether or not external auth methods can auto-register users.
   */
  oauthRegistration: boolean;
  /**
   * A default time range limit to apply to post sorts, in seconds.
   */
  defaultPostTimeRangeSeconds?: number;
  /**
   * Block NSFW content being created
   */
  disallowSelfPromotionContent: boolean;
  users: bigint;
  posts: bigint;
  proposals: bigint;
  communities: bigint;
  /**
   * The number of users with any activity in the last day.
   */
  usersActiveDay: bigint;
  /**
   * The number of users with any activity in the last week.
   */
  usersActiveWeek: bigint;
  /**
   * The number of users with any activity in the last month.
   */
  usersActiveMonth: bigint;
  /**
   * The number of users with any activity in the last half year.
   */
  usersActiveHalfYear: bigint;
  /**
   * Dont send multilang notifications to users for new replies, mentions etc
   */
  disableEmailNotifications: boolean;
  verifyWithOtp: boolean;
  /**
   * The coin used by this platform
   */
  coinId?: CoinId;
  name: string;
  /**
   * A sidebar for the site in markdown.
   */
  sidebar?: string;
  /**
   * A shorter, one-line description of the site.
   */
  description?: string;
  /**
   * An icon URL.
   */
  icon?: DbUrl;
  /**
   * A banner url.
   */
  banner?: DbUrl;
  /**
   * If present, self_promotion content is visible by default. Should be displayed by
   * frontends/clients when the site is first opened by a user.
   */
  contentWarning?: string;
};
