// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The post sort types.
 */
export type PostSortType =
  | "Active"
  | "Hot"
  | "New"
  | "Old"
  | "Top"
  | "MostProposals"
  | "NewProposals"
  | "Controversial"
  | "Scaled";
