// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {DbUrl} from "./DbUrl";
import type {PersonId} from "./PersonId";
import type {PostId} from "./PostId";
import {IntendedUse} from "./IntendedUse";
import {JobType} from "./JobType";

/**
 * A post.
 */
export type Post = {
  id: PostId;
  name: string;
  /**
   * An optional link / url for the post.
   */
  url?: DbUrl;
  /**
   * An optional post body, in markdown.
   */
  body?: string;
  creatorId: PersonId;
  categoryId: CategoryId;
  /**
   * Whether the post is removed.
   */
  removed: boolean;
  /**
   * Whether the post is locked.
   */
  locked: boolean;
  publishedAt: string;
  updatedAt?: string;
  /**
   * Whether the post is deleted.
   */
  deleted: boolean;
  /**
   * Whether the post is NSFW.
   */
  nsfw: boolean;
  /**
   * A title for the link.
   */
  embedTitle?: string;
  /**
   * A description for the link.
   */
  embedDescription?: string;
  /**
   * A thumbnail picture url.
   */
  thumbnailUrl?: DbUrl;
  /**
   * A video url for the link.
   */
  embedVideoUrl?: DbUrl;
  /**
   * Whether the post is featured to its category.
   */
  featuredCategory: boolean;
  /**
   * Whether the post is featured to its site.
   */
  featuredLocal: boolean;
  urlContentType?: string;
  /**
   * An optional alt_text, usable for image posts.
   */
  altText?: string;
  /**
   * Time at which the post will be published. None means publish immediately.
   */
  scheduledPublishTimeAt?: string;
  proposals: number;
  score: number;
  upvotes: number;
  downvotes: number;
  /**
   * The time of the newest proposal in the post.
   */
  newestProposalTimeAt: string;
  reportCount: number;
  unresolvedReportCount: number;
  pending: boolean;
  intendedUse: IntendedUse;
  jobType: JobType;
  budget: number;
  deadline?: string;
  isEnglishRequired: boolean;
};
