// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PostNotificationsMode} from "./PostNotificationsMode";

export type PostActions = {
  /**
   * When the post was read.
   */
  readAt?: string;
  /**
   * When was the last time you read the proposals.
   */
  readProposalsAt?: string;
  /**
   * The number of proposals you read last. Subtract this from total proposals to get an unread
   * count.
   */
  readProposalsAmount?: number;
  /**
   * When the post was liked.
   */
  likedAt?: string;
  /**
   * The like / score of the post.
   */
  likeScore?: number;
  /**
   * When the post was hidden.
   */
  hiddenAt?: string;
  notifications?: PostNotificationsMode;
};
