// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PostLogisticsView} from "./PostLogisticsView";
import type {PostView} from "./PostView";

export type PostResponse = { postView: PostView, 
/**
 * Unified logistics view for Delivery or Ride posts (None for Normal)
 */
logistics?: PostLogisticsView, };
