// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {CategoryActions} from "./CategoryActions";
import type {ImageDetails} from "./ImageDetails";
import type {InstanceActions} from "./InstanceActions";
import type {Person} from "./Person";
import type {PersonActions} from "./PersonActions";
import type {Post} from "./Post";
import type {PostActions} from "./PostActions";
import type {TagsView} from "./TagsView";

/**
 * A post view.
 */
export type PostView = {
    post: Post;
    creator: Person;
    /**
     * Optional for delivery posts (which rely on post_kind for distinction).
     * Matches `pub category: Option<Category>` in api-108jobs
     * crates/db/src/source/post_view/mod.rs.
     */
    category?: Category;
    imageDetails?: ImageDetails;
    categoryActions?: CategoryActions;
    personActions?: PersonActions;
    postActions?: PostActions;
    instanceActions?: InstanceActions;
    creatorIsAdmin: boolean;
    tags: TagsView;
    canMod: boolean;
    creatorBanned: boolean;
    creatorIsModerator: boolean;
    creatorBannedFromCategory: boolean;
};
