// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of post: Normal | Delivery | RideTaxi
 */
export type PostKind = "Normal" | "Delivery" | "RideTaxi";
