// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {DeliveryDetailsView} from "./DeliveryDetailsView";
import type {RideSessionView} from "./RideSessionView";

export type PostLogisticsView = { "kind": "delivery", "view": DeliveryDetailsView } | { "kind": "ride", "view": RideSessionView };
