// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProposalActions = {
  /**
   * The like / score for the comment.
   */
  likeScore?: number;
  /**
   * When the comment was liked.
   */
  likedAt?: string;
};
