// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {Person} from "./Person";
import type {PersonActions} from "./PersonActions";
import type {PersonBan} from "./PersonBan";
import type {Post} from "./Post";
import type {Proposal} from "./Proposal";
import type {ProposalActions} from "./ProposalActions";
import type {TagsView} from "./TagsView";

/**
 * A proposal view.
 */
export type ProposalView = { proposal: Proposal, creator: Person, post: Post, category?: Category, proposalActions?: ProposalActions, personActions?: PersonActions, 
/**
 * Renamed from the old per-instance actions embed (your own block/ban state);
 * `#[serde(rename)]` keeps the wire shape unchanged (only the ban half of the old embed
 * survives -- blocking was dead).
 */
instanceActions?: PersonBan, creatorIsAdmin: boolean, postTags: TagsView, canMod: boolean, creatorBanned: boolean, creatorIsModerator: boolean, creatorBannedFromCategory: boolean, };
