// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ProposalId} from "./ProposalId";
import type {PersonId} from "./PersonId";
import type {PostId} from "./PostId";

/**
 * A proposal.
 */
export type Proposal = {
  id: ProposalId;
  creatorId: PersonId;
  postId: PostId;
  content: string;
  /**
   * Whether the comment has been removed.
   */
  removed: boolean;
  publishedAt: string;
  updatedAt?: string;
  /**
   * Whether the comment has been deleted by its creator.
   */
  deleted: boolean;
  /**
   * The path / tree location of a comment, separated by dots, ending with the comment's id. Ex:
   * 0.24.27
   */
  path: string;
  /**
   * Whether the comment has been distinguished(speaking officially) by a mod.
   */
  distinguished: boolean;
  score: number;
  upvotes: number;
  downvotes: number;
  /**
   * The total number of children in this comment branch.
   */
  childCount: number;
  reportCount: number;
  unresolvedReportCount: number;
  pending: boolean;
};
