// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {WorkflowId} from "./WorkflowId";

/**
 * Request revision on a submitted work (employer requests changes from freelancer).
 */
export type RequestRevisionForm = { seqNumber: number, workflowId: WorkflowId, reason?: string, };
