// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {RidePrivate} from "./RidePrivate";
import type {RidePublic} from "./RidePublic";

export type RideSessionView = { "type": "public", "data": RidePublic } | { "type": "private", "data": RidePrivate };
