// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PaymentMethod} from "./PaymentMethod";
import type {VehicleType} from "./VehicleType";

/**
 * Minimal payload to create a RideSession attached to a post
 */
export type RideSessionCreatePayload = { pickupAddress: string, pickupLat?: number, pickupLng?: number, dropoffAddress: string, dropoffLat?: number, dropoffLng?: number, pickupNote?: string, passengerName?: string, passengerPhone?: string, dropoffNote?: string, dropoffContactName?: string, dropoffContactPhone?: string, 
/**
 * When the customer travels. Absent = now.
 */
departAt?: string, 
/**
 * When bidding closes and the sweep may pick for an undecided passenger.
 * Absent = this ride takes no bids.
 */
biddingClosesAt?: string, paymentMethod: PaymentMethod, 
/**
 * The route the app already measured, so the SERVER can price it.
 *
 * The app has these two numbers from Google Routes before it ever shows a
 * fare. Sending them -- and only them -- is what moves the rate from the
 * phone to the server without buying a server-side Maps key, an API bill
 * and a round trip of latency. Note what is deliberately absent: there is
 * no price field here and there must never be one. A tampered client can
 * overstate its distance, which is a visible and checkable lie; being able
 * to name its own fare would let it raise its own bid ceiling.
 *
 * Both optional, and both stay optional. A ride requested with no route
 * measurement is still a ride -- older app builds send none, and two
 * addresses that were never geocoded have no route between them. The fare
 * is then unknown, which is the state every ride was in before this field
 * existed.
 */
distanceM?: number, durationS?: number, 
/**
 * Which kind of vehicle the passenger picked.
 *
 * This is the passenger's half of the rider match: `list_available_rides`
 * shows a rider only the jobs their own `rider.vehicle_type` can serve, and
 * `place_bid` and `claim_ride_session` refuse the ones it cannot. Before
 * this field existed nothing anywhere recorded the choice, so a motorcycle
 * rider could win a "Standard Car" auction and the passenger got the wrong
 * vehicle at a price quoted for a different one.
 *
 * Optional, and it stays optional. Absent means *the passenger did not
 * say*, and an unspecified ride is offered to EVERY rider -- see
 * `RideSession::vehicle_may_serve`. Every app build that has not shipped
 * the picker sends nothing here and must keep working exactly as it does
 * today; making this required, or defaulting it server-side to a vehicle
 * nobody chose, are the two ways to break that silently.
 *
 * JSON: `"requestedVehicleType": "Motorcycle" | "Car"` -- the variant names
 * verbatim, capitalised, matching how `VehicleType` already crosses the
 * wire everywhere else (`rider.vehicleType`, `pricingConfig.vehicleType`).
 * Note `camelCase` renames the FIELD, not the value. There is no `Bicycle`:
 * 2026-08-14-000001 removed it, because a bicycle cannot hold the Ry17/Ry18
 * for-hire registration that carrying a passenger for money requires.
 *
 * It should agree with the `pricing_config` row the passenger was quoted
 * from, but it is not validated against one and deliberately so: the quote
 * is best-effort (no route measurement, no active rate card, and the fare
 * is simply unknown), and refusing a ride because the fare lookup failed
 * would turn a missing price into a missing ride.
 */
requestedVehicleType?: VehicleType, };
