// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ListingType} from "./ListingType";
import type {PostListingMode} from "./PostListingMode";
import type {PostSortType} from "./PostSortType";
import type {ProposalSortType} from "./ProposalSortType";
import type {SensitiveString} from "./SensitiveString";
import type {VoteShow} from "./VoteShow";
import {PortfolioPic} from "./PortfolioPic";
import {WorkSample} from "./WorkSample";

/**
 * Saves settings for your profile.
 */
export type SaveUserSettings = {
    /**
     * Show nsfw posts.
     */
    showNsfw?: boolean;
    /**
     * Blur nsfw posts.
     */
    blurNsfw?: boolean;
    /**
     * Your profile's theme.
     */
    theme?: string;
    /**
     * The default post listing type, usually "local"
     */
    defaultListingType?: ListingType;
    /**
     * A post-view mode that changes how multiple post listings look.
     */
    postListingMode?: PostListingMode;
    /**
     * The default post sort, usually "active"
     */
    defaultPostSortType?: PostSortType;
    /**
     * A default time range limit to apply to post sorts, in seconds. 0 means none.
     */
    defaultPostTimeRangeSeconds?: number;
    /**
     * The default proposal sort, usually "hot"
     */
    defaultProposalSortType?: ProposalSortType;
    /**
     * The language of the interface
     */
    interfaceLanguage?: string;
    /**
     * Your email.
     */
    email?: SensitiveString;
    /**
     * Your bio / info, in markdown.
     */
    displayName?: string;
    bio?: string;
    username?: string;
    avatarUrl?: string;
    /**
     * Your resume/CV file URL
     */
    resumeUrl?: string;
    /**
     * The original filename of the uploaded resume
     */
    resumeFileName?: string;
    /**
     * Your matrix profile id. Ex: @myUser:matrix.org
     */
    matrixUserId?: string;
    /**
     * Whether to show or hide avatars.
     */
    showAvatars?: boolean;
    /**
     * Sends notifications to your email.
     */
    sendNotificationsToEmail?: boolean;
    /**
     * Whether this account is a bot account. Users can hide these accounts easily if they wish.
     */
    botAccount?: boolean;
    /**
     * Whether to show bot accounts.
     */
    showBotAccounts?: boolean;
    /**
     * Whether to show read posts.
     */
    showReadPosts?: boolean;
    blockingKeywords?: Array<string>;
    /**
     * Open links in a new tab
     */
    openLinksInNewTab?: boolean;
    /**
     * Enable infinite scroll
     */
    infiniteScrollEnabled?: boolean;
    /**
     * Whether to allow keyboard navigation (for browsing and interacting with posts and proposals).
     */
    enableKeyboardNavigation?: boolean;
    /**
     * Whether profile avatars or inline images in the UI that are gifs should be allowed to play or
     * should be paused
     */
    enableAnimatedImages?: boolean;
    /**
     * Whether a profile can send / receive private messages
     */
    enablePrivateMessages?: boolean;
    /**
     * Whether to auto-collapse bot proposals.
     */
    collapseBotProposals?: boolean;
    /**
     * Some vote display mode settings
     */
    showScores?: boolean;
    showUpvotes?: boolean;
    showDownvotes?: VoteShow;
    showUpvotePercentage?: boolean;
    /**
     * Whether to automatically mark fetched posts as read.
     */
    autoMarkFetchedPostsAsRead?: boolean;
    /**
     * Whether to hide posts containing images/videos.
     */
    hideMedia?: boolean;
    /**
     * Whether to show vote totals given to others.
     */
    showPersonVotes?: boolean;
    /**
     * Your contacts (e.g., "LineID:xxx|Facebook:yyy|Email:zzz|Phone:aaa")
     */
    contacts?: string,
    /**
     * Your skills
     */
    skills?: string,
    /**
     * Your portfolio pictures to prove your quality
     */
    portfolioPics?: Array<PortfolioPic>,
    /**
     * Your work samples to prove your quality
     */
    workSamples?: Array<WorkSample>,
    /**
     * Whether you are currently available for new jobs
     */
    available?: boolean,
    /**
     * Whether to encrypt this account's chat messages in transit.
     */
    secureChatEnabled?: boolean;
};
