// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {Coin} from "./Coin";
import type {IntendedUse} from "./IntendedUse";
import type {JobType} from "./JobType";
import type {ListingType} from "./ListingType";
import type {PaginationCursor} from "./PaginationCursor";
import type {PersonId} from "./PersonId";
import type {PostKind} from "./PostKind";
import type {SearchSortType} from "./SearchSortType";
import type {SearchType} from "./SearchType";
import type {TripStatus} from "./TripStatus";

/**
 * Searches the site, given a search term, and some optional filters.
 */
export type Search = { q?: string, categoryId?: CategoryId, categoryName?: string, creatorId?: PersonId, type?: SearchType, sort?: SearchSortType, 
/**
 * Filter to within a given time range, in seconds.
 * IE 60 would give results for the past minute.
 */
timeRangeSeconds?: number, listingType?: ListingType, 
/**
 * If true, then show the self_promotion posts (even if your user setting is to hide them)
 */
selfPromotion?: boolean, intendedUse?: IntendedUse, jobType?: JobType, 
/**
 * Minimum budget in cents (Coin type)
 */
budgetMin?: Coin, 
/**
 * Maximum budget in cents (Coin type)
 */
budgetMax?: Coin, requiresEnglish?: boolean, postKind?: PostKind, 
/**
 * Filter by logistics status (Pending, InProgress, Completed, etc.) for Delivery/RideTaxi posts
 */
logisticsStatus?: TripStatus, pageCursor?: PaginationCursor, pageBack?: boolean, limit?: number, };
