// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {ImageDetails} from "./ImageDetails";
import type {Person} from "./Person";
import type {PersonActions} from "./PersonActions";
import type {PersonBan} from "./PersonBan";
import type {Post} from "./Post";
import type {PostActions} from "./PostActions";
import type {PostLogisticsView} from "./PostLogisticsView";
import type {TagsView} from "./TagsView";

/**
 * A post view with logistics for search results
 */
export type SearchPostView = { 
/**
 * Logistics data for Delivery/RideTaxi posts
 */
logistics?: PostLogisticsView, post: Post, creator: Person, 
/**
 * Category is optional for delivery posts (which rely on post_kind for distinction)
 */
category?: Category, imageDetails?: ImageDetails, personActions?: PersonActions, postActions?: PostActions, 
/**
 * Renamed from the old per-instance actions embed (representing your own block/ban state
 * against the item's instance); `#[serde(rename)]` keeps the wire shape unchanged now that the
 * Rust-side type/field is `person_ban`/`PersonBan` (the block half of the old embed is gone --
 * it was dead -- only the ban half survives).
 */
instanceActions?: PersonBan, creatorIsAdmin: boolean, tags: TagsView, canMod: boolean, creatorBanned: boolean, creatorIsModerator: boolean, creatorBannedFromCategory: boolean, };
