// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {WorkflowId} from "./WorkflowId";

/**
 * Submit completed work (freelancer starts work).
 */
export type SubmitStartWorkForm = { seqNumber: number, workflowId: WorkflowId, workDescription: string, deliverableUrl?: string, };
