// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {TagId} from "./TagId";

/**
 * A tag that can be assigned to a post within a category.
 * The tag object is created by the category moderators.
 * The assignment happens by the post creator and can be updated by the category moderators.
 *
 * A tag is a federatable object that gives additional context to another object, which can be
 * displayed and filtered on. Currently, we only have category post tags, which is a tag that is
 * created by the mods of a category, then assigned to posts by post authors as well as mods of a
 * category, to categorize a post.
 *
 * In the future we may add more tag types, depending on the requirements, this will lead to either
 * expansion of this table (category_id optional, addition of tag_type enum) or split of this
 * table / creation of new tables.
 *
 * Serialize-only camelCase: `Tag` is serialized outward into HTTP responses (`Json<Tag>` from
 * create/update/delete-tag handlers, and embedded via `TagsView` on `PostView`/`ProposalView`/
 * `CategoryView`/`SearchCombinedViewInternal`), but deserialized only from Postgres'
 * `json_agg(tag.*)` (see
 * `crate::utils::queries::post_tags_fragment`/`category_post_tags_fragment` and
 * `impl FromSql<Nullable<Json>, Pg> for TagsView`), which emits the real, snake_case column
 * names no matter what this attribute says. A plain `rename_all = "camelCase"` would make
 * deserialize expect the camelCase spelling too and break every post/proposal/category read
 * that has a tag attached. Renaming only the serialize direction keeps HTTP responses camelCase
 * while deserialization still matches what Postgres actually sends.
 */
export type Tag = { id: TagId, displayName: string, 
/**
 * the category that owns this tag
 */
categoryId: CategoryId, publishedAt: string, updatedAt?: string, deleted: boolean, };
