// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport workflow status - works for both cargo delivery and taxi rides
 * Taxi flow: Pending → Assigned → RiderConfirmed → EnRouteToPickup → PickedUp → EnRouteToDropoff →
 * Delivered Cargo flow: Pending → Assigned → EnRouteToPickup → PickedUp → EnRouteToDropoff →
 * Delivered
 */
export type TripStatus = "Pending" | "Assigned" | "RiderConfirmed" | "EnRouteToPickup" | "PickedUp" | "EnRouteToDropoff" | "Delivered" | "Cancelled";
