// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankAccountId} from "./BankAccountId";
import type {BankId} from "./BankId";

/**
 * Update an existing bank account for user.
 */
export type UpdateBankAccount = { bankAccountId: BankAccountId, bankId?: BankId, accountNumber?: string, accountName?: string, isDefault?: boolean, verificationImage?: string, };
