// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The billing status for escrow workflow
 */
export type WorkflowStatus = "WaitForFreelancerQuotation" | "QuotationPendingReview" | "OrderApproved" | "InProgress" | "PendingEmployerReview" | "Completed" | "Cancelled";
