// HAND-WRITTEN, not generated by ts-rs -- see the note in `TermsStatusResponse.ts`.

import type {AppKind} from "./AppKind";

/**
 * `POST /api/v4/account/terms/accept`
 *
 * `termsVersion` must equal the version the server currently has in force for
 * that app; the server rejects a mismatch rather than recording it. Send back
 * the version that came from `TermsStatusResponse`, never a value the client
 * remembers from an earlier session -- a stale one is exactly the case the
 * server-side check exists to catch.
 *
 * There is no user id in the body on purpose: the server takes it from the JWT,
 * so one account cannot accept terms on another's behalf.
 */
export type AcceptTermsRequest = {
  app: AppKind;
  termsVersion: string;
};
