// HAND-WRITTEN, not generated by ts-rs -- see the note in `TermsStatusResponse.ts`.

import type {AppKind} from "./AppKind";

/**
 * What came back on record. Deliberately NOT the whole consent row: the `ip`
 * and `userAgent` the server stored are the evidence of the acceptance, not
 * information the client asked for, and echoing them would put the audit trail
 * into every client log and response cache.
 */
export type AcceptTermsResponse = {
  app: AppKind;
  termsVersion: string;
  acceptedAt: string;
};
