// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AddressId} from "./AddressId";

export type Address = {
    id: AddressId,
    addressLine1: string,
    addressLine2?: string,
    subdistrict?: string,
    district: string,
    province: string,
    postalCode: string,
    countryId: string,
    isDefault: boolean,
    createdAt: string,
    updatedAt: string,
};
