// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ผู้ใช้คนเดียวกันใช้ได้ทั้งสองแอป แต่ยอมรับเงื่อนไขแยกกัน — เจ้าของสั่ง 2026-08-27
 * `Jobs` = 108jobs.com (ตลาดงาน) · `Ride` = 108heros.com (เรียกรถ/ส่งของ)
 *
 * ไม่มี `#[default]` โดยตั้งใจ: การ default ไปแอปใดแอปหนึ่งคือช่องทางเดียว
 * ที่ทำให้ consent รั่วข้ามแอปได้ ทุก call site ต้องระบุแอปเอง
 */
export type AppKind = "Jobs" | "Ride";
