// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BillingId} from "./BillingId";
import type {ChatRoomId} from "./ChatRoomId";
import type {WorkflowId} from "./WorkflowId";

/**
 * Approve work and release payment (employer approves).
 */
export type ApproveWorkForm = { seqNumber: number, workflowId: WorkflowId, roomId: ChatRoomId, billingId: BillingId, };
