// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BillingId} from "./BillingId";
import type {WalletId} from "./WalletId";
import type {WorkflowId} from "./WorkflowId";

/**
 * Approve quotation and convert to order (employer approves freelancer's quotation).
 */
export type ApproveQuotationForm = { seqNumber: number, billingId: BillingId, walletId: WalletId, workflowId: WorkflowId, };
