// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Bank} from "./Bank";
import type {BankAccount} from "./BankAccount";

/**
 * A user bank account view with bank information.
 */
export type BankAccountView = { userBankAccount: BankAccount, bank: Bank, };
