// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankId} from "./BankId";

export type Bank = { id: BankId, name: string, countryId: string, bankCode?: string, swiftCode?: string, isActive?: boolean, createdAt: string, updatedAt?: string, };
