// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BillingId} from "./BillingId";
import type {ChatRoomId} from "./ChatRoomId";
import type {Coin} from "./Coin";
import type {LocalUserId} from "./LocalUserId";
import type {PostId} from "./PostId";
import type {ProposalId} from "./ProposalId";

/**
 * A billing/invoice created by freelancer for job work.
 */
export type Billing = { id: BillingId, 
/**
 * The freelancer who created this billing
 */
freelancerId: LocalUserId, 
/**
 * The employer who needs to pay this billing
 */
employerId: LocalUserId, 
/**
 * The job post this billing is for
 */
postId: PostId, 
/**
 * The proposal/proposal this billing relates to
 */
proposalId?: ProposalId, 
/**
 * Amount to be paid
 */
amount: Coin, 
/**
 * Description of work to be done
 */
description: string, 
/**
 * Current status of the billing
 */
status: string, 
/**
 * Submitted work description
 */
workDescription?: string, 
/**
 * URL to deliverable files
 */
deliverableUrl?: string, 
/**
 * When the billing was created
 */
createdAt: string, 
/**
 * When the billing was last updated
 */
updatedAt?: string, 
/**
 * When the billing was paid (if paid)
 */
paidAt?: string, roomId?: ChatRoomId, };
