// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The category sort types. See here for descriptions: https://join-app_108heros.org/docs/en/users/03-votes-and-ranking.html
 */
export type CategorySortType = "Hot" | "New" | "Old" | "NameAsc" | "NameDesc" | "Proposals" | "Posts" | "Subscribers";
