// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {CategoryFollowerState} from "./CategoryFollowerState";

export type CategoryActions = {
    /**
     * When the category was followed.
     */
    followedAt?: string;
    /**
     * The state of the category follow.
     */
    followAtate?: CategoryFollowerState;
    /**
     * When the category was blocked.
     */
    blockedAt?: string;
    /**
     * When this profile became a moderator.
     */
    becameModeratorAt?: string;
    /**
     * When this profile received a ban.
     */
    receivedBanAt?: string;
    /**
     * When their ban expires.
     */
    banExpiresAt?: string;
};
