// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import {Category} from "./Category";

/**
 * A category node view.
 */
export interface CategoryNodeView {
    category: Category;
    children?: CategoryNodeView[];
}
