// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {Person} from "./Person";

/**
 * A category moderator.
 */
export type CategoryModeratorView = {
    category: Category;
    moderator: Person;
};
