// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { ChatParticipantView } from "./ChatParticipantView";
import type { ChatRoom } from "./ChatRoom";
import type { PostPreview } from "./PostPreview";
import type { Workflow } from "./Workflow";

export type ChatRoomView = { room: ChatRoom, participants: Array<ChatParticipantView>, post?: PostPreview, lastMessage?: ChatMessage, workflow?: Workflow, };
