// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ChatRoomId} from "./ChatRoomId";
import type {PaginationCursor} from "./PaginationCursor";

/**
 * Query params for fetching chat message history for a room.
 */
export type ChatHistoryQuery = {
  roomId: ChatRoomId;
  /** Cursor returned by a previous response to fetch the next/prev page */
  cursor?: PaginationCursor;
  /** Maximum number of items to return */
  limit?: number;
  /** When true with a cursor, page backwards instead of forwards */
  back?: boolean;
};
