// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRoomId } from "./ChatRoomId";
import type { DbUrl } from "./DbUrl";
import type { LocalUserId } from "./LocalUserId";
import type { PersonId } from "./PersonId";

export type ChatParticipantView = { id: LocalUserId, personId: PersonId, name: string, displayName?: string, avatar?: DbUrl, available: boolean, roomId: ChatRoomId, joinedAt: string, };
