// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRoomId } from "./ChatRoomId";
import type { PostId } from "./PostId";
import type { ProposalId } from "./ProposalId";
import type { SerialId } from "./SerialId";

export type ChatRoom = { id: ChatRoomId, roomName: string | null, createdAt: string, updatedAt: string | null, postId: PostId | null, currentProposalId: ProposalId | null, lastMessageId: string | null, lastMessageAt: string | null, serialId: SerialId, 
/**
 * When this room stopped accepting new messages, or `None` while it is
 * still open.
 *
 * A ride's room is closed when the ride ends. History stays readable —
 * what was agreed on the way to the pickup is the passenger's own record —
 * so this gates sending only. See `ChatRoom::send_state` and the
 * `is_room_open` gate it feeds on the send path.
 */
closedAt: string | null, };
