// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { ChatRoom } from "./ChatRoom";
import type { LocalUser } from "./LocalUser";

export type ChatMessageView = { message: ChatMessage, sender: LocalUser, room: ChatRoom, };
