// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageView } from "./ChatMessageView";
import type { PaginationCursor } from "./PaginationCursor";

/**
 * The chat messages response, mirroring SearchResponse shape
 */
export type ChatMessagesResponse = { results: Array<ChatMessageView>, 
/**
 * the pagination cursor to use to fetch the next page
 */
nextPage?: PaginationCursor, prevPage?: PaginationCursor, };
