// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ContactId} from "./ContactId";

export type Contact = {
    id: ContactId,
    phone?: string,
    email?: string,
    secondaryEmail?: string,
    lineId?: string,
    facebook?: string,
    createdAt: string,
    updatedAt: string,
};
