// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BillingStatus} from "./BillingStatus";
import type {ChatRoomId} from "./ChatRoomId";
import type {Coin} from "./Coin";
import type {LocalUserId} from "./LocalUserId";
import type {PostId} from "./PostId";
import type {ProposalId} from "./ProposalId";
import type {WorkflowId} from "./WorkflowId";

/**
 * Create invoice/quotation for job (freelancer creates detailed proposal).
 */
export type CreateInvoiceForm = { employerId: LocalUserId, postId: PostId, proposalId?: ProposalId, seqNumber: number, amount: Coin, proposal: string, projectName: string, status: BillingStatus, projectDetails: string, workingDays: number, deliverables: Array<string>, note?: string, startingDay: string, deliveryDay: string, roomId: ChatRoomId, workflowId: WorkflowId, };
