// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BillingId} from "./BillingId";
import type {BillingStatus} from "./BillingStatus";
import type {Coin} from "./Coin";
import type {LocalUserId} from "./LocalUserId";
import type {PostId} from "./PostId";

/**
 * Response for creating an invoice.
 */
export type CreateInvoiceResponse = { billingId: BillingId, issuerId: LocalUserId, recipientId: LocalUserId, postId: PostId, amount: Coin, status: BillingStatus, createdAt: string, success: boolean, };
