// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRoomId } from "./ChatRoomId";
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";
import type { ProposalId } from "./ProposalId";

export type CreateChatRoomRequest = { partnerPersonId: PersonId, roomId?: ChatRoomId, postId?: PostId, currentProposalId?: ProposalId, roomName?: string, };
