// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Create a tag for a category.
 */
export type CreateCategoryTag = {
    categoryId: CategoryId;
    displayName: string;
};
