// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ProposalId} from "./ProposalId";
import type {PostId} from "./PostId";

/**
 * Create a proposal.
 */
export type CreateProposal = {
  content: string;
  postId: PostId;
  parentId?: ProposalId;
};
