// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Delete or restore a category.
 */
export type DeleteCategory = {
  categoryId: CategoryId;
  /**
   * `true` deletes, `false` restores.
   */
  deleted: boolean;
};
