// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {TagId} from "./TagId";

/**
 * Delete a category tag.
 */
export type DeleteCategoryTag = {
  tagId: TagId;
};
