// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Coin} from "./Coin";
import type {DeliveryDetailsId} from "./DeliveryDetailsId";
import type {PersonId} from "./PersonId";
import type {PostId} from "./PostId";
import type {ProposalId} from "./ProposalId";
import type {RiderId} from "./RiderId";
import type {VehicleType} from "./VehicleType";

/**
 * Private version of delivery details - includes all information.
 * Only visible to the employer, assigned rider, and admins.
 */
export type DeliveryDetailsPrivate = { id: DeliveryDetailsId, postId: PostId, pickupAddress: string, pickupLat?: number, pickupLng?: number, dropoffAddress: string, dropoffLat?: number, dropoffLng?: number, packageDescription?: string, packageWeightKg?: number, packageSize?: string, fragile: boolean, requiresSignature: boolean, vehicleRequired?: VehicleType, latestPickupAt?: string, latestDropoffAt?: string, senderName?: string, senderPhone?: string, receiverName?: string, receiverPhone?: string, cashOnDelivery: boolean, codAmount?: number, status: string, cancellationReason?: string, assignedRiderId?: RiderId, assignedAt?: string, assignedByPersonId?: PersonId, linkedProposalId?: ProposalId, deliveryFee: Coin, employerConfirmedAt?: string, employerWalletTransactionId?: number, riderWalletTransactionId?: number, createdAt: string, updatedAt: string, };
