// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {DeliveryDetailsPrivate} from "./DeliveryDetailsPrivate";
import type {DeliveryDetailsPublic} from "./DeliveryDetailsPublic";

/**
 * A wrapper that can be either public or private based on viewer authorization.
 * Use this in API responses to automatically filter sensitive data.
 */
export type DeliveryDetailsView = DeliveryDetailsPublic | DeliveryDetailsPrivate;
