// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ProposalId} from "./ProposalId";

/**
 * Edit a proposal.
 */
export type EditProposal = {
  proposalId: ProposalId;
  content?: string;
};
