// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";

/**
 * Get a category. Must provide either an id, or a name.
 */
export type GetCategory = {
  id?: CategoryId;
  /**
   * Example: star_trek , or star_trek@xyz.tld
   */
  name?: string;
};
