// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {Coin} from "./Coin";
import type {IntendedUse} from "./IntendedUse";
import type {JobType} from "./JobType";
import type {ListingType} from "./ListingType";
import type {PaginationCursor} from "./PaginationCursor";
import type {PostKind} from "./PostKind";
import type {PostSortType} from "./PostSortType";
import type {TripStatus} from "./TripStatus";

/**
 * Get a list of posts.
 */
export type GetPosts = { type?: ListingType, sort?: PostSortType, 
/**
 * Filter to within a given time range, in seconds.
 * IE 60 would give results for the past minute.
 * Use Zero to override the local_site and local_user time_range.
 */
timeRangeSeconds?: number, categoryId?: CategoryId, showHidden?: boolean, 
/**
 * If true, then show the read posts (even if your user setting is to hide them)
 */
showRead?: boolean, 
/**
 * If true, then show the self_promotion posts (even if your user setting is to hide them)
 */
selfPromotion?: boolean, 
/**
 * If false, then show posts with media attached (even if your user setting is to hide them)
 */
hideMedia?: boolean, 
/**
 * If true, then only show posts with no proposals
 */
noProposalsOnly?: boolean, intendedUse?: IntendedUse, jobType?: JobType, 
/**
 * Minimum budget in cents (Coin type)
 */
budgetMin?: Coin, 
/**
 * Maximum budget in cents (Coin type)
 */
budgetMax?: Coin, requiresEnglish?: boolean, postKind?: PostKind, 
/**
 * Filter by logistics status (Pending, InProgress, Completed, etc.) for Delivery/RideTaxi posts
 */
logisticsStatus?: TripStatus, pageCursor?: PaginationCursor, pageBack?: boolean, limit?: number, };
