// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PaginationCursor} from "./PaginationCursor";
import type {PostItem} from "./PostItem";

/**
 * The post list response.
 */
export type GetPostsResponse = { posts: Array<PostItem>, 
/**
 * the pagination cursor to use to fetch the next page
 */
nextPage?: PaginationCursor, prevPage?: PaginationCursor, };
