// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ProposalView} from "./ProposalView";
import type {PaginationCursor} from "./PaginationCursor";

/**
 * The proposal list response (backend field is 'proposals').
 */
export type GetProposalsResponse = {
  proposals: Array<ProposalView>;
  nextPage?: PaginationCursor;
  prevPage?: PaginationCursor;
};
