// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PostId} from "./PostId";
import type {ProposalId} from "./ProposalId";

/**
 * Get a post. Needs either the post id, or proposal_id.
 */
export type GetPost = { id?: PostId, proposalId?: ProposalId, };
