// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {OAuthProvider} from "./OAuthProvider";
import type {PersonView} from "./PersonView";
import type {PluginMetadata} from "./PluginMetadata";
import type {PublicOAuthProvider} from "./PublicOAuthProvider";
import type {SiteView} from "./SiteView";
import type {Tagline} from "./Tagline";

/**
 * An expanded response for a site.
 */
export type GetSiteResponse = {
  siteView: SiteView;
  admins: Array<PersonView>;
  version: string;
  /**
   * If the site has any taglines, a random one is included here for displaying
   */
  tagline?: Tagline;
  /**
   * A list of external auth methods your site supports.
   */
  oauthProviders: Array<PublicOAuthProvider>;
  adminOauthProviders: Array<OAuthProvider>;
  imageUploadDisabled: boolean;
  activePlugins: Array<PluginMetadata>;
};
