// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {AddressId} from "./AddressId";
import type {IdentityCardId} from "./IdentityCardId";

export type IdentityCard = {
    id: IdentityCardId,
    addressId: AddressId,
    idNumber: string,
    issuedDate: string,
    expiryDate: string,
    fullName: string,
    dateOfBirth: string,
    nationality: string,
    isVerified: boolean,
    createdAt: string,
};
