// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceActions = {
  /**
   * When the instance was blocked.
   */
  blockedAt?: string;
  /**
   * When this profile received a site ban.
   */
  receivedBanAt?: string;
  /**
   * When their ban expires.
   */
  banExpiresAt?: string;
};
