// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageRefId } from "./ChatMessageRefId";
import type { ChatRoomId } from "./ChatRoomId";
import type { LocalUserId } from "./LocalUserId";

export type LastRead = { localUserId: LocalUserId, roomId: ChatRoomId, lastReadMsgId?: ChatMessageRefId, updatedAt?: string, };
