// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRoomView } from "./ChatRoomView";
import type { PaginationCursor } from "./PaginationCursor";

export type ListUserChatRoomsResponse = { rooms: Array<ChatRoomView>, 
/**
 * the pagination cursor to use to fetch the next page
 */
nextPage?: PaginationCursor, prevPage?: PaginationCursor, };
