// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PaginationCursor} from "./PaginationCursor";
import {ChatRoomView} from "./ChatRoomView";

/**
 * The response for listing the user's chat rooms.
 */
export type ListUserChatRoomsResponse = {
    rooms: ChatRoomView[];
    /** the pagination cursor to use to fetch the next page */
    nextPage?: PaginationCursor;
    /** the pagination cursor to use to fetch the previous page */
    prevPage?: PaginationCursor;
};
