// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PaginationCursor} from "./PaginationCursor";

/**
 * Get your profile's image / media uploads.
 */
export type ListMedia = {
  pageCursor?: PaginationCursor;
  pageBack?: boolean;
  limit?: number;
};
