// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PaginationCursor} from "./PaginationCursor";

/**
 * Query params for listing a user's chat rooms.
 * Supports both traditional limit-based pagination and cursor-based pagination.
 */
export type ListUserChatRoomsQuery = {
    /** Maximum number of items to return */
    limit?: number;
    /** Cursor returned by a previous response to fetch the next page */
    pageCursor?: PaginationCursor;
    /** When true with a pageCursor, page backwards instead of forwards */
    pageBack?: boolean;
};
