// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PaginationCursor} from "./PaginationCursor";

export type ListBankAccountQuery = { 
/**
 * `ts(type = "number")` because `bigint` is over-faithful here and costs the
 * client real ergonomics for no safety. `limit_fetch` refuses anything
 * outside `1..=FETCH_LIMIT_MAX` (50), so this can never approach the range
 * where an `i64` stops fitting a JavaScript `number` -- while `bigint`
 * forces every caller to write `limit: 5n` and makes an ordinary numeric
 * literal a type error. Same escape hatch `billing/api.rs` already uses.
 */
limit?: number, isVerified?: boolean, isDefault?: boolean, year?: number, month?: number, day?: number, pageCursor?: PaginationCursor, pageBack?: boolean, };
