// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankAccountView} from "./BankAccountView";
import type {PaginationCursor} from "./PaginationCursor";

/**
 * List unverified bank accounts (admin only).
 */
export type ListBankAccountsResponse = { bankAccounts: Array<BankAccountView>, nextPage?: PaginationCursor, prevPage?: PaginationCursor, };
