// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategorySortType} from "./CategorySortType";
import type {ListingType} from "./ListingType";
import type {PaginationCursor} from "./PaginationCursor";

/**
 * Fetches a list of categories.
 */
export type ListCategories = {
  type_?: ListingType;
  sort?: CategorySortType;
  /**
   * Filter to within a given time range, in seconds.
   * IE 60 would give results for the past minute.
   */
  timeRangeSeconds?: number;
  maxDepth?: number;
  showNsfw?: boolean;
  pageCursor?: PaginationCursor;
  pageBack?: boolean;
  limit?: number;
};
