// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {SensitiveString} from "./SensitiveString";

/**
 * Log in to 108heros.
 *
 * Note: Banned users can still log in, to be able to do certain things like delete
 * their account.
 */
export type Login = {
  usernameOrEmail: SensitiveString;
  password: SensitiveString;
  /**
   * May be required, if totp is enabled for their account.
   */
  totp2faToken?: string;
};
