// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Category} from "./Category";
import type {Instance} from "./Instance";
import type {LocalUserView} from "./LocalUserView";
import type {Person} from "./Person";
import type {ProfileDataView} from "./ProfileDataView";
import type {Wallet} from "./Wallet";

/**
 * Your user info.
 */
export type MyUserInfo = {
    localUserView: LocalUserView,
    categoryBlocks: Array<Category>,
    instanceBlocks: Array<Instance>,
    personBlocks: Array<Person>,
    keywordBlocks: Array<string>,
    wallet: Wallet,
    profile: ProfileDataView,
    isRider: boolean,
};
