// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {OAuthProviderId} from "./OAuthProviderId";

/**
 * oauth providers with client_secret - should never be sent to the client
 */
export type OAuthProvider = {
  id: OAuthProviderId;
  /**
   * The OAuth 2.0 providers name displayed to the profile on the Login page
   */
  displayName: string;
  /**
   * The issuer url of the OAUTH providers.
   */
  issuer: string;
  /**
   * The authorization endpoint is used to interact with the resource owner and obtain an
   * authorization grant. This is usually provided by the OAUTH providers.
   */
  authorizationEndpoint: string;
  /**
   * The token endpoint is used by the client to obtain an access token by presenting its
   * authorization grant or refresh token. This is usually provided by the OAUTH providers.
   */
  tokenEndpoint: string;
  /**
   * The UserInfo Endpoint is an OAuth 2.0 Protected Resource that returns Claims about the
   * authenticated End-User. This is defined in the OIDC specification.
   */
  userinfoEndpoint: string;
  /**
   * The OAuth 2.0 claim containing the unique profile ID returned by the providers. Usually this
   * should be set to "sub".
   */
  idClaim: string;
  /**
   * The client_id is provided by the OAuth 2.0 providers and is a unique identifier to this
   * service
   */
  clientId: string;
  /**
   * Lists the scopes requested from users. Users will have to grant access to the requested scope
   * at sign up.
   */
  scopes: string;
  /**
   * Automatically sets email as verified on registration
   */
  autoVerifyEmail: boolean;
  /**
   * Allows linking an OAUTH account to an existing profile account by matching emails
   */
  accountLinkingEnabled: boolean;
  /**
   * switch to enable or disable an oauth providers
   */
  enabled: boolean;
  publishedAt: string;
  updatedAt?: string;
  /**
   * switch to enable or disable PKCE
   */
  usePkce: boolean;
};
