// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalUserId } from "./LocalUserId";

/**
 * Query params for fetching a peer's read/presence status.
 */
export type PeerStatusQuery = { peerId: LocalUserId, };
