// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {LocalUserId} from "./LocalUserId";
import {ChatRoomId} from "./ChatRoomId";

/**
 * Query params for fetching the peer status.
 */
export type PeerStatusQuery = {
    peerId: LocalUserId;
};
