// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {LocalSiteId} from "./LocalSiteId";

/**
 * Rate limits for your site. Given in count / length of time.
 */
export type PlatformRateLimitConfig = {
  platformConfigId: LocalSiteId;
  messageMaxRequests: number;
  messageIntervalSeconds: number;
  postMaxRequests: number;
  postIntervalSeconds: number;
  registerMaxRequests: number;
  registerIntervalSeconds: number;
  imageMaxRequests: number;
  imageIntervalSeconds: number;
  proposalMaxRequests: number;
  proposalIntervalSeconds: number;
  searchMaxRequests: number;
  searchIntervalSeconds: number;
  publishedAt: string;
  updatedAt?: string;
  importUserSettingsMaxRequests: number;
  importUserSettingsIntervalSeconds: number;
};
