// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coin } from "./Coin";
import type { PersonId } from "./PersonId";
import type { PostId } from "./PostId";

/**
 * View only
 */
export type PostPreview = { id: PostId, name: string, budget: Coin, deadline?: string, creatorId: PersonId, };
