// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryId} from "./CategoryId";
import type {Coin} from "./Coin";
import type {DbUrl} from "./DbUrl";
import type {IntendedUse} from "./IntendedUse";
import type {JobType} from "./JobType";
import type {PersonId} from "./PersonId";
import type {PostId} from "./PostId";
import type {PostKind} from "./PostKind";

/**
 * A post.
 */
export type Post = { id: PostId, name: string, 
/**
 * An optional link / url for the post.
 */
url?: DbUrl, 
/**
 * An optional post body, in markdown.
 */
body?: string, creatorId: PersonId, 
/**
 * Category ID (nullable for delivery posts, which rely on post_kind for distinction)
 */
categoryId?: CategoryId, 
/**
 * Whether the post is removed.
 */
removed: boolean, 
/**
 * Whether the post is locked.
 */
locked: boolean, publishedAt: string, updatedAt?: string, 
/**
 * Whether the post is deleted.
 */
deleted: boolean, 
/**
 * Whether the post is NSFW.
 */
selfPromotion: boolean, 
/**
 * A title for the link.
 */
embedTitle?: string, 
/**
 * A description for the link.
 */
embedDescription?: string, 
/**
 * A thumbnail picture url.
 */
thumbnailUrl?: DbUrl, 
/**
 * A video url for the link.
 */
embedVideoUrl?: DbUrl, 
/**
 * Whether the post is featured to its category.
 */
featuredCategory: boolean, 
/**
 * Whether the post is featured to its site.
 */
featuredLocal: boolean, urlContentType?: string, 
/**
 * An optional alt_text, usable for image posts.
 */
altText?: string, 
/**
 * Time at which the post will be published. None means publish immediately.
 */
scheduledPublishTimeAt?: string, proposals: number, score: number, upvotes: number, downvotes: number, 
/**
 * The time of the newest proposal in the post.
 */
newestProposalTimeAt: string, 
/**
 * Always 0. The report system (and the DB triggers that used to maintain this counter) was
 * deleted; the live `post` table no longer has a `report_count` column at all. This field is
 * kept, hardcoded to 0, only because it's `required` (non-nullable) in a Flutter domain
 * entity -- see the `report_count`/`unresolved_report_count` pseudo-columns on the local
 * `post` module above for how this is wired to a SQL literal instead of a real column.
 */
reportCount: number, 
/**
 * Always 0. See `report_count`.
 */
unresolvedReportCount: number, pending: boolean, isEnglishRequired: boolean, budget: Coin, deadline?: string, jobType: JobType, intendedUse: IntendedUse, postKind: PostKind, };
