// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Address} from "./Address";
import type {Contact} from "./Contact";
import type {IdentityCard} from "./IdentityCard";

/**
 * A ProfileData view.
 */
export type ProfileDataView = {
    contact: Contact,
    address: Address,
    identityCard: IdentityCard,
    showCountrySelectionBox: boolean,
    isNewBuyer: boolean,
};
