// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The proposal sort types. See here for descriptions: https://join-app_108heros.org/docs/en/users/03-votes-and-ranking.html
 */
export type ProposalSortType = "Hot" | "Top" | "New" | "Old" | "Controversial";
