// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PersonId} from "./PersonId";
import type {PostId} from "./PostId";
import type {ProposalId} from "./ProposalId";

/**
 * A proposal.
 */
export type Proposal = { id: ProposalId, creatorId: PersonId, postId: PostId, content: string, 
/**
 * Whether the proposal has been removed.
 */
removed: boolean, publishedAt: string, updatedAt?: string, 
/**
 * Whether the proposal has been deleted by its creator.
 */
deleted: boolean, 
/**
 * The path / tree location of a proposal, separated by dots, ending with the proposal's id. Ex:
 * 0.24.27
 */
path: string, 
/**
 * Whether the proposal has been distinguished(speaking officially) by a mod.
 */
distinguished: boolean, score: number, upvotes: number, downvotes: number, 
/**
 * The total number of children in this proposal branch.
 */
childCount: number, 
/**
 * Always 0. The report system (and the DB triggers that used to maintain this counter) was
 * deleted; the live `proposal` table no longer has a `report_count` column at all. This field
 * is kept, hardcoded to 0, only because it's `required` (non-nullable) in a Flutter domain
 * entity -- see the `report_count`/`unresolved_report_count` pseudo-columns on the local
 * `proposal` module above for how this is wired to a SQL literal instead of a real column.
 */
reportCount: number, 
/**
 * Always 0. See `report_count`.
 */
unresolvedReportCount: number, pending: boolean, };
