// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PostId} from "./PostId";
import type {RideSessionId} from "./RideSessionId";
import type {RiderId} from "./RiderId";
import type {TripStatus} from "./TripStatus";

export type RidePublic = { id: RideSessionId, postId: PostId, pickupAddress: string, dropoffAddress: string, status: TripStatus, riderId?: RiderId, riderAssignedAt?: string, departAt?: string, biddingClosesAt?: string, 
/**
 * The ceiling a bid on this ride is measured against, and the one number in
 * `RidePublic` that decides money.
 *
 * `place_bid` refuses anything above `ride_session.quoted_fare_coin` with
 * `BidExceedsQuotedFare { max_price_coin }`. Until this field existed
 * `RidePublic` carried no fare at all, so the rider being asked to name a
 * price was never shown the limit their price had to fall under -- the app
 * could neither display it nor validate against it, and the only way to
 * learn the number was to be refused and read it out of the error. A rule
 * enforced against a number the person subject to it cannot see is not a
 * rule, it is a guessing game.
 *
 * Public on purpose, in the same register as `depart_at` /
 * `bidding_closes_at` above: this is the passenger's own quote for a job
 * they are advertising to riders, priced by the server from the route --
 * the asking price on a listing, not a fact about a person. It says nothing
 * about who the passenger is, and the only caller that can read a
 * `RidePublic` at all is an approved rider on `/rides/available` (the post
 * feed's Public arm returns no ride block whatsoever -- see
 * `ride_logistics_for_viewer`), which is to say: exactly the audience the
 * number is for.
 *
 * `standard_fare_coin` and `demand_multiplier` deliberately do NOT follow
 * it. Only this number binds a bid; the standard fare is a second figure
 * that binds nothing and can sit on either side of the quote now that
 * `approved_demand_multiplier` can raise it, so showing both would leave a
 * rider to guess which one they are bidding against. `demand_multiplier` is
 * worse than redundant: it is the raw supply/demand *signal*, stored even
 * when it was not applied, so publishing it would show riders a surge that
 * is not being paid. Whatever demand did that a rider stands to earn is
 * already inside this number.
 *
 * `None`, and stays optional, for every ride quoted before the quote
 * columns existed and for every request that arrives with no route
 * measurement. It must never be read as zero or defaulted: `None` here
 * means *this ride has no ceiling* (`BidCeiling::Unquoted`, an unbounded
 * bid), not *this ride is free*.
 */
quotedFareCoin?: number, };
