// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {LocalUserId} from "./LocalUserId";
import type {PaymentMethod} from "./PaymentMethod";
import type {PostId} from "./PostId";
import type {PricingConfigId} from "./PricingConfigId";
import type {RideSessionId} from "./RideSessionId";
import type {RiderId} from "./RiderId";
import type {TripStatus} from "./TripStatus";

export type RidePrivate = { id: RideSessionId, postId: PostId, employerId: LocalUserId, riderId?: RiderId, pricingConfigId?: PricingConfigId, pickupAddress: string, pickupLat?: number, pickupLng?: number, dropoffAddress: string, dropoffLat?: number, dropoffLng?: number, pickupNote?: string, passengerName?: string, passengerPhone?: string, dropoffNote?: string, dropoffContactName?: string, dropoffContactPhone?: string, departAt?: string, biddingClosesAt?: string, paymentMethod: PaymentMethod, paymentStatus?: string, status: TripStatus, requestedAt: string, riderAssignedAt?: string, riderConfirmedAt?: string, arrivedAtPickupAt?: string, rideStartedAt?: string, rideCompletedAt?: string, 
/**
 * The same bid ceiling `RidePublic` carries, and here for the same reason
 * every other `RidePublic` field is also here: `RidePrivate` is the
 * unredacted view, so a field it lacks that the Public view has would mean
 * the projection hands *less* to the party entitled to *more*. It is also
 * the passenger's own quote, and the passenger reads this struct.
 *
 * Three prices sit next to each other and they are not interchangeable:
 * this is the ceiling bids were measured against (written once at request
 * time), `current_price_coin` is what the winning bid agreed, and
 * `final_price_coin` is what the completed trip charged.
 */
quotedFareCoin?: number, currentPriceCoin?: number, totalDistanceKm?: number, totalDurationMinutes?: number, finalPriceCoin?: number, baseFareAppliedCoin?: number, timeChargeAppliedCoin?: number, distanceChargeAppliedCoin?: number, cancellationReason?: string, createdAt: string, updatedAt?: string, };
