// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


/**
 * Saves settings for your profile.
 */
export type SavePerson = {
  displayName?: string;
  name?: string;
  avatar?: string;
  bio?: string;
  skills?: string;
};
