// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Saves settings for your profile.
 */
export type SaveAddress = {
  country?: string;
  province?: string;
  districtOrSubdistrict?: string;
  subdistrictOrDistrict?: string;
  addressDetails?: string;
  zipCode?: string;
};
