// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import {SavePerson} from "./SavePerson";
import {SaveAddress} from "./SaveAddress";
import {SaveCard} from "./SaveCard";

/**
 * Saves settings for your profile.
 */
export type SaveUserProfile = {
  updatePerson: SavePerson;
  card: SaveCard;
  updateAddress: SaveAddress;
};
