// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {CategoryView} from "./CategoryView";
import type {PersonView} from "./PersonView";
import type {ProposalView} from "./ProposalView";
import type {SearchPostView} from "./SearchPostView";

export type SearchCombinedView = { "type_": "Post" } & SearchPostView | { "type_": "Proposal" } & ProposalView | { "type_": "Category" } & CategoryView | { "type_": "Person" } & PersonView;
