// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankAccountId} from "./BankAccountId";

/**
 * Set default bank account.
 */
export type SetDefaultBankAccount = { bankAccountId: BankAccountId, };
