// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Instance} from "./Instance";
import type {PlatformConfig} from "./PlatformConfig";
import type {PlatformRateLimitConfig} from "./PlatformRateLimitConfig";

/**
 * A site view.
 */
export type SiteView = {
  localSite: PlatformConfig;
  localSiteRateLimit: PlatformRateLimitConfig;
  instance: Instance;
};
