// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {ChatRoomId} from "./ChatRoomId";
import type {PostId} from "./PostId";

/**
 * Start or init a workflow for a post/sequence in a chat room.
 */
export type StartWorkflowForm = { postId: PostId, seqNumber: number, roomId: ChatRoomId, };
