// HAND-WRITTEN, not generated by ts-rs -- unlike its neighbours in this folder.
//
// The API struct it mirrors (`crates/http/src/api/local_user/terms.rs`,
// `TermsStatusResponse`) carries only `Serialize`/`Deserialize`, no
// `#[cfg_attr(feature = "ts-rs", derive(ts_rs::TS))]`, so nothing generates a
// binding for it and this file cannot be refreshed by re-running the export.
// That means it WILL drift silently the moment the Rust struct changes: there
// is no compile step on either side that compares the two.
//
// Fix upstream, don't paper over it here -- api-108heros needs the ts-rs
// derives on all three terms types, after which this file should be deleted
// and replaced by the generated one.

/**
 * `GET /api/v4/account/terms`
 *
 * The versions currently in force plus whether THIS user is on record for each
 * one. Both flags are `false` for an unauthenticated caller -- the endpoint is
 * deliberately readable logged-out so an app can show the terms before login.
 *
 * A flag is per-app AND per-version: accepting Jobs v1 leaves `jobsAccepted`
 * false the moment the active version moves to v2, which is the whole point of
 * versioning the consent rather than storing a boolean.
 */
export type TermsStatusResponse = {
  jobsVersion: string;
  rideVersion: string;
  jobsAccepted: boolean;
  rideAccepted: boolean;
};
