// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BankAccountId} from "./BankAccountId";

/**
 * Verify a bank account (admin only).
 */
export type VerifyBankAccount = { bankAccountId: BankAccountId, };
