// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import {Person} from "./Person";

/**
 * The response for a profile visit.
 */
export type VisitProfileResponse = {
    profile: Person;
};
