// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {WalletId} from "./WalletId";
import {Coin} from "./Coin";

/**
 * A user wallet for managing balance and transactions.
 */
export type Wallet = {
    id: WalletId,
    /**
     * Available balance for spending
     */
    balanceTotal: Coin,
    balanceAvailable: Coin,
    balanceOutstanding: Coin,
    isPlatform: boolean,
    createdAt: string,
    updatedAt?: string,
    /**
     * Monotonic write counter. Bumped on every balance mutation. See
     * backend migration 2026-05-25_add_wallet_versioning_and_hold_ledger.
     */
    version: number,
};
