// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {BillingId} from "./BillingId";
import type {ChatRoomId} from "./ChatRoomId";
import type {PostId} from "./PostId";
import type {WorkflowId} from "./WorkflowId";
import type {WorkflowStatus} from "./WorkflowStatus";

export type Workflow = { id: WorkflowId, postId: PostId, seqNumber: number, status: WorkflowStatus, revisionRequired: boolean, revisionCount: number, revisionReason?: string, deliverableVersion: number, deliverableSubmittedAt?: string, deliverableAccepted: boolean, acceptedAt?: string, createdAt: string, updatedAt?: string, roomId?: ChatRoomId, deliverableUrl?: string, active: boolean, statusBeforeCancel?: WorkflowStatus, billingId?: BillingId, };
