// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {WorkflowId} from "./WorkflowId";
import type {WorkflowStatus} from "./WorkflowStatus";

export type WorkFlowOperationResponse = { workflowId: WorkflowId, status: WorkflowStatus, success: boolean, };
